### ISSUE TITLE
corebot command error..

### ISSUE THREAD

**Issue by ThomasADavis** [outofcoffee/corebot#43]
Lastest version, using docker pull

this used to work:

@corebot command 

but in the lastest release, I had to change it to 

@corebot command something where something is a variable.  ie from config:

    elasticsearch_nodes:
        jobId: 89423a16-c0c0-41b5-xxxxxxxxxxxx
        template: elastic health
        showJobOutput: true
        tags:
            - dae
            - elasticsearch

used to work, now for it work I have to change it to:

    elasticsearch_nodes:
        jobId: 89423a16-c0c0-41b5-xxxxxxxxxxxx
        template: elastic health [something]
        showJobOutput: true
        tags:
            - dae
            - elasticsearch

and it works. 

the error we get is:

java.util.NoSuchElementException: Collection is empty.

and the docker logs show:

```
05:05:01.600 [Grizzly(1)] INFO  com.gatehill.corebot.chat.MessageService - Performing operation: ActionOperation(operationType=OperationType(name='TRIGGER', description='trigger job'), actionConfig=ActionConfig(template=elastic nodes, jobId=89423a16-c0c0-41b5-8fc6-659f3de42fbf, name=elasticsearch_nodes, options={}, tags=[all, dae, elasticsearch], driver=rundeck, showJobOutput=true, showJobOutcome=true, runAsTriggerUser=false), args={})
05:05:01.600 [Grizzly(1)] DEBUG com.gatehill.corebot.security.AuthorisationService - User 'clwhitney' operation TRIGGER: PERMITTED
05:05:01.882 [Grizzly(1)] ERROR com.gatehill.corebot.chat.MessageService - Error performing action operation ActionOperation(operationType=OperationType(name='TRIGGER', description='trigger job'), actionConfig=ActionConfig(template=elastic nodes, jobId=89423a16-c0c0-41b5-8fc6-659f3de42fbf, name=elasticsearch_nodes, options={}, tags=[all, dae, elasticsearch], driver=rundeck, showJobOutput=true, showJobOutcome=true, runAsTriggerUser=false), args={})
java.util.concurrent.CompletionException: java.util.NoSuchElementException: Collection is empty.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_141]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_141]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647) ~[?:1.8.0_141]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:669) ~[?:1.8.0_141]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:1997) ~[?:1.8.0_141]
	at com.gatehill.corebot.chat.MessageService.performActionOperation(MessageService.kt:138) [frontends-common-1.1.1.Final.jar:?]
	at com.gatehill.corebot.chat.MessageService.access$performActionOperation(MessageService.kt:25) [frontends-common-1.1.1.Final.jar:?]
	at com.gatehill.corebot.chat.MessageService$performOperation$1.invoke(MessageService.kt:112) [frontends-common-1.1.1.Final.jar:?]
	at com.gatehill.corebot.chat.MessageService$performOperation$1.invoke(MessageService.kt:25) [frontends-common-1.1.1.Final.jar:?]
	at com.gatehill.corebot.security.AuthorisationService.checkPermission(AuthorisationService.kt:29) [core-engine-1.1.1.Final.jar:?]
	at com.gatehill.corebot.chat.MessageService.performOperation(MessageService.kt:102) [frontends-common-1.1.1.Final.jar:?]
	at com.gatehill.corebot.chat.MessageService.handleMessage(MessageService.kt:44) [frontends-common-1.1.1.Final.jar:?]
	at com.gatehill.corebot.frontend.slack.chat.SlackChatServiceImpl$messagePostedListeners$1$$special$$inlined$let$lambda$1.invoke(SlackChatServiceImpl.kt:67) [frontends-slack-1.1.1.Final.jar:?]
	at com.gatehill.corebot.frontend.slack.chat.SlackChatServiceImpl$messagePostedListeners$1$$special$$inlined$let$lambda$1.invoke(SlackChatServiceImpl.kt:22) [frontends-slack-1.1.1.Final.jar:?]
	at com.gatehill.corebot.frontend.slack.chat.SlackChatServiceImpl.executeBotAction(SlackChatServiceImpl.kt:111) [frontends-slack-1.1.1.Final.jar:?]
	at com.gatehill.corebot.frontend.slack.chat.SlackChatServiceImpl$messagePostedListeners$1.onEvent(SlackChatServiceImpl.kt:65) [frontends-slack-1.1.1.Final.jar:?]
	at com.gatehill.corebot.frontend.slack.chat.SlackChatServiceImpl$messagePostedListeners$1.onEvent(SlackChatServiceImpl.kt:47) [frontends-slack-1.1.1.Final.jar:?]
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl$EventDispatcher.dispatchImpl(SlackWebSocketSessionImpl.java:241) [simple-slack-api-0c58385.jar:?]
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl$EventDispatcher.dispatch(SlackWebSocketSessionImpl.java:198) [simple-slack-api-0c58385.jar:?]
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.onMessage(SlackWebSocketSessionImpl.java:970) [simple-slack-api-0c58385.jar:?]
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.onMessage(SlackWebSocketSessionImpl.java:54) [simple-slack-api-0c58385.jar:?]
	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:562) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:812) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:200) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.frame.TextFrame.respond(TextFrame.java:135) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:635) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:664) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:472) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:114) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:270) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565) [tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545) [tyrus-standalone-client-1.8.3.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.util.NoSuchElementException: Collection is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:166) ~[kotlin-stdlib-1.1.51.jar:1.1.51]
	at com.gatehill.corebot.backend.jobs.service.BaseJobTriggerService$trigger$2.invoke(BaseJobTriggerService.kt:46) ~[backends-deployment-jobs-1.1.1.Final.jar:?]
	at com.gatehill.corebot.backend.jobs.service.BaseJobTriggerService$trigger$2.invoke(BaseJobTriggerService.kt:22) ~[backends-deployment-jobs-1.1.1.Final.jar:?]
	at com.gatehill.corebot.action.LockService.checkActionLock(LockService.kt:85) ~[core-engine-1.1.1.Final.jar:?]
	at com.gatehill.corebot.backend.jobs.service.BaseJobTriggerService.trigger(BaseJobTriggerService.kt:40) ~[backends-deployment-jobs-1.1.1.Final.jar:?]
	at com.gatehill.corebot.backend.jobs.action.JobBaseActionDriver.handleAction(JobBaseActionDriver.kt:25) ~[backends-deployment-jobs-1.1.1.Final.jar:?]
	at com.gatehill.corebot.backend.rundeck.action.RundeckActionDriverImpl.handleAction(RundeckActionDriver.kt:44) ~[backends-deployment-rundeck-1.1.1.Final.jar:?]
	at com.gatehill.corebot.driver.BaseActionDriver.perform(BaseActionDriver.kt:30) ~[core-engine-1.1.1.Final.jar:?]
	at com.gatehill.corebot.bot.action.DirectActionPerformServiceImpl.perform(DirectActionPerformServiceImpl.kt:20) ~[bots-common-1.1.1.Final.jar:?]
	... 40 more
```

**Comment by outofcoffee** [comment]
Thanks for the report, @ThomasADavis - looking at this now.

**Comment by outofcoffee** [comment]
@ThomasADavis I've pushed a candidate fix to the `hotfix/1.1.2` branch. It should build a Docker image with the tag `1.1.2-SNAPSHOT` with this in shortly.

You should be able to use the following (temporary) Docker image when it's built:

    outofcoffee/corebot:1.1.2-SNAPSHOT

Please could you let me know if this resolves your problem and we'll get it merged into `master`.

**Comment by ThomasADavis** [comment]
Thanks, that fixes it!

**Comment by outofcoffee** [comment]
Thanks, @ThomasADavis 👍
