### ISSUE TITLE
corebot fails to locate action file

### ISSUE THREAD

**Issue by sinaiy** [outofcoffee/corebot#56]
`corebot_1  | java.io.FileNotFoundException: /opt/corebot/actions.yml (No such file or directory)
corebot_1  |    at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_171]
corebot_1  |    at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_171]
corebot_1  |    at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_171]
`
i created the file as instructed, in /opt/corebot
the file is under the ownership of the user and can be read (or edited by him)

i built it locally and am executing through `docker-compose up`

thank you for your time and assitance

sinai

**Comment by babvin** [comment]
I'm getting the same error
java.io.FileNotFoundException: /opt/corebot/actions.yml

**Comment by outofcoffee** [comment]
Hi @sinaiy please could you post your compose file?

**Comment by babvin** [comment]
Hi
I don't have system.yml   can you please share

/opt/corebot$ ls -laht
total 124K
drwxr-xr-x 15 vsa  vsa  4.0K Aug  4 05:45 .
-rwxrwxrwx  1 vsa  vsa   526 Aug  4 05:45 docker-compose.yml
-rw-r--r--  1 root root  552 Aug  4 05:38 1
drwxr-xr-x  6 root root 4.0K Aug  4 03:54 ..
-rwxrwxrwx  1 vsa  vsa   139 Aug  4 03:40 actions.yml
drwxr-xr-x  4 vsa  vsa  4.0K Aug  4 02:52 build
drwxr-xr-x  4 vsa  vsa  4.0K Aug  4 02:52 .gradle
-rw-r--r--  1 vsa  vsa    88 Feb  4  2018 .gitignore
-rw-r--r--  1 vsa  vsa  5.2K Feb  4  2018 CHANGELOG.md
-rw-r--r--  1 vsa  vsa   16K Feb  4  2018 README.md
drwxr-xr-x  5 vsa  vsa  4.0K Feb  4  2018 backends
drwxr-xr-x  8 vsa  vsa  4.0K Feb  4  2018 bots
-rw-r--r--  1 vsa  vsa  1.4K Feb  4  2018 build.gradle
-rw-r--r--  1 vsa  vsa   503 Feb  4  2018 circle.yml
drwxr-xr-x  6 vsa  vsa  4.0K Feb  4  2018 core
drwxr-xr-x  4 vsa  vsa  4.0K Feb  4  2018 docs
drwxr-xr-x  7 vsa  vsa  4.0K Feb  4  2018 examples
drwxr-xr-x  7 vsa  vsa  4.0K Feb  4  2018 frontends
drwxr-xr-x  3 vsa  vsa  4.0K Feb  4  2018 gradle
-rwxr-xr-x  1 vsa  vsa  5.2K Feb  4  2018 gradlew
-rw-r--r--  1 vsa  vsa  2.2K Feb  4  2018 gradlew.bat
drwxr-xr-x 13 vsa  vsa  4.0K Feb  4  2018 plugins
drwxr-xr-x  2 vsa  vsa  4.0K Feb  4  2018 scripts
-rw-r--r--  1 vsa  vsa  2.8K Feb  4  2018 settings.gradle
drwxr-xr-x  6 vsa  vsa  4.0K Feb  4  2018 stores
drwxr-xr-x  4 vsa  vsa  4.0K Feb  4  2018 test
