### ISSUE TITLE
corebot looses it's connection to slack.

### ISSUE THREAD

**Issue by ThomasADavis** [outofcoffee/corebot#57]
I'm not sure what is causing this error, but corebot stops responding after a while.

`
18:32:45.358 [Thread-1] WARN  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - Connection lost...
18:32:45.497 [Thread-1] INFO  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - slack session ready
18:32:45.497 [Grizzly(1)] WARN  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - event of type UNKNOWN not handled: com.ullink.slack.simpleslackapi.events.SlackEvent$1@a716239
18:33:15.497 [Thread-1] ERROR com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - unexpected exception on monitoring thread 
java.io.IOException: java.lang.IllegalStateException: Connection is not open.
	at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.processFuture(TyrusRemoteEndpoint.java:166) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.sendText(TyrusRemoteEndpoint.java:100) ~[tyrus-standalone-client-1.8.3.jar:?]
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl$2.run(SlackWebSocketSessionImpl.java:443) [simple-slack-api-0c58385.jar:?]
Caused by: java.lang.IllegalStateException: Connection is not open.
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyWriter.write(GrizzlyWriter.java:74) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.write(ProtocolHandler.java:315) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:211) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:206) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:238) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.TyrusWebSocket.sendText(TyrusWebSocket.java:292) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.sendText(TyrusRemoteEndpoint.java:98) ~[tyrus-standalone-client-1.8.3.jar:?]
	... 1 more
18:33:45.498 [Thread-1] WARN  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - Connection lost...
18:33:45.629 [Grizzly(1)] WARN  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - event of type UNKNOWN not handled: com.ullink.slack.simpleslackapi.events.SlackEvent$1@a716239
18:33:45.629 [Thread-1] INFO  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - slack session ready
18:34:15.629 [Thread-1] ERROR com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - unexpected exception on monitoring thread 
java.io.IOException: java.lang.IllegalStateException: Connection is not open.
	at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.processFuture(TyrusRemoteEndpoint.java:166) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.sendText(TyrusRemoteEndpoint.java:100) ~[tyrus-standalone-client-1.8.3.jar:?]
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl$2.run(SlackWebSocketSessionImpl.java:443) [simple-slack-api-0c58385.jar:?]
Caused by: java.lang.IllegalStateException: Connection is not open.
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyWriter.write(GrizzlyWriter.java:74) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.write(ProtocolHandler.java:315) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:211) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:206) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:238) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.TyrusWebSocket.sendText(TyrusWebSocket.java:292) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.sendText(TyrusRemoteEndpoint.java:98) ~[tyrus-standalone-client-1.8.3.jar:?]
	... 1 more
18:34:45.629 [Thread-1] WARN  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - Connection lost...
18:34:45.774 [Thread-1] INFO  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - slack session ready
18:34:45.774 [Grizzly(1)] WARN  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - event of type UNKNOWN not handled: com.ullink.slack.simpleslackapi.events.SlackEvent$1@a716239
18:35:15.774 [Thread-1] ERROR com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - unexpected exception on monitoring thread 
java.io.IOException: java.lang.IllegalStateException: Connection is not open.
	at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.processFuture(TyrusRemoteEndpoint.java:166) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.sendText(TyrusRemoteEndpoint.java:100) ~[tyrus-standalone-client-1.8.3.jar:?]
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl$2.run(SlackWebSocketSessionImpl.java:443) [simple-slack-api-0c58385.jar:?]
Caused by: java.lang.IllegalStateException: Connection is not open.
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyWriter.write(GrizzlyWriter.java:74) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.write(ProtocolHandler.java:315) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:211) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:206) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:238) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.TyrusWebSocket.sendText(TyrusWebSocket.java:292) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.sendText(TyrusRemoteEndpoint.java:98) ~[tyrus-standalone-client-1.8.3.jar:?]
	... 1 more
18:35:45.775 [Thread-1] WARN  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - Connection lost...
18:35:46.070 [Grizzly(1)] WARN  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - event of type UNKNOWN not handled: com.ullink.slack.simpleslackapi.events.SlackEvent$1@a716239
18:35:46.071 [Thread-1] INFO  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - slack session ready
18:36:16.071 [Thread-1] ERROR com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - unexpected exception on monitoring thread 
java.io.IOException: java.lang.IllegalStateException: Connection is not open.
	at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.processFuture(TyrusRemoteEndpoint.java:166) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.sendText(TyrusRemoteEndpoint.java:100) ~[tyrus-standalone-client-1.8.3.jar:?]
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl$2.run(SlackWebSocketSessionImpl.java:443) [simple-slack-api-0c58385.jar:?]
Caused by: java.lang.IllegalStateException: Connection is not open.
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyWriter.write(GrizzlyWriter.java:74) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.write(ProtocolHandler.java:315) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:211) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:206) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:238) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.TyrusWebSocket.sendText(TyrusWebSocket.java:292) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.sendText(TyrusRemoteEndpoint.java:98) ~[tyrus-standalone-client-1.8.3.jar:?]
	... 1 more
18:36:46.071 [Thread-1] WARN  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - Connection lost...
18:36:46.206 [Thread-1] INFO  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - slack session ready
18:36:46.206 [Grizzly(1)] WARN  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - event of type UNKNOWN not handled: com.ullink.slack.simpleslackapi.events.SlackEvent$1@a716239
18:37:16.207 [Thread-1] ERROR com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - unexpected exception on monitoring thread 
java.io.IOException: java.lang.IllegalStateException: Connection is not open.
	at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.processFuture(TyrusRemoteEndpoint.java:166) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.sendText(TyrusRemoteEndpoint.java:100) ~[tyrus-standalone-client-1.8.3.jar:?]
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl$2.run(SlackWebSocketSessionImpl.java:443) [simple-slack-api-0c58385.jar:?]
Caused by: java.lang.IllegalStateException: Connection is not open.
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyWriter.write(GrizzlyWriter.java:74) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.write(ProtocolHandler.java:315) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:211) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:206) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:238) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.TyrusWebSocket.sendText(TyrusWebSocket.java:292) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.sendText(TyrusRemoteEndpoint.java:98) ~[tyrus-standalone-client-1.8.3.jar:?]
	... 1 more
18:37:46.207 [Thread-1] WARN  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - Connection lost...
18:37:46.352 [Thread-1] INFO  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - slack session ready
18:37:46.352 [Grizzly(1)] WARN  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - event of type UNKNOWN not handled: com.ullink.slack.simpleslackapi.events.SlackEvent$1@a716239
18:38:16.352 [Thread-1] ERROR com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - unexpected exception on monitoring thread 
java.io.IOException: java.lang.IllegalStateException: Connection is not open.
	at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.processFuture(TyrusRemoteEndpoint.java:166) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.sendText(TyrusRemoteEndpoint.java:100) ~[tyrus-standalone-client-1.8.3.jar:?]
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl$2.run(SlackWebSocketSessionImpl.java:443) [simple-slack-api-0c58385.jar:?]
Caused by: java.lang.IllegalStateException: Connection is not open.
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyWriter.write(GrizzlyWriter.java:74) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.write(ProtocolHandler.java:315) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:211) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:206) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:238) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.TyrusWebSocket.sendText(TyrusWebSocket.java:292) ~[tyrus-standalone-client-1.8.3.jar:?]
	at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.sendText(TyrusRemoteEndpoint.java:98) ~[tyrus-standalone-client-1.8.3.jar:?]
	... 1 more
`

**Comment by outofcoffee** [comment]
Thank you - raised https://github.com/outofcoffee/corebot/issues/69 to look at replacing the library.
