### ISSUE TITLE
java.io.FileNotFoundException: /opt/corebot/actions.yml

### ISSUE THREAD

**Issue by babvin** [outofcoffee/corebot#58]
Getting below error while starting corebot locally

**java.io.FileNotFoundException: /opt/corebot/actions.yml (No such file or directory)**  

`sudo docker-compose up 
Creating network "corebot_default" with the default driver
Creating corebot_corebot_1 ... done
Attaching to corebot_corebot_1
corebot_1  | 07:55:18.052 [main] DEBUG com.gatehill.corebot.bot.Bot$Builder - Installing injection module: com.gatehill.corebot.bot.BotModule
corebot_1  | 07:55:18.082 [main] DEBUG com.gatehill.corebot.store.DataStoreModule - Using 'lockStore' data store implementation: com.gatehill.corebot.store.InMemoryDataStoreImpl
corebot_1  | 07:55:18.107 [main] DEBUG com.gatehill.corebot.bot.Bot$Builder - Installing injection module: com.gatehill.corebot.frontend.slack.SlackModule
corebot_1  | 07:55:18.508 [main] DEBUG com.gatehill.corebot.driver.ActionDriverFactory - Registering 'jenkins' driver: com.gatehill.corebot.backend.jenkins.action.JenkinsActionDriver
corebot_1  | 07:55:18.509 [main] DEBUG com.gatehill.corebot.driver.ActionDriverFactory - Registering 'rundeck' driver: com.gatehill.corebot.backend.rundeck.action.RundeckActionDriver
corebot_1  | 07:55:18.517 [main] INFO  com.gatehill.corebot.frontend.slack.chat.SlackSessionServiceImpl - Connecting to Slack...
corebot_1  | 07:55:18.534 [main] INFO  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - connecting to slack
corebot_1  | 07:55:20.487 [main] INFO  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - Team T029J4LQQ : xxx
corebot_1  | 07:55:20.487 [main] INFO  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - Self U5Z0J6A0K : jobframework
corebot_1  | 07:55:20.487 [main] INFO  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - 3576 users found on this session
corebot_1  | 07:55:20.488 [main] INFO  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - 3535 channels found on this session
corebot_1  | 07:55:21.132 [Grizzly(2)] WARN  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - event of type UNKNOWN not handled: com.ullink.slack.simpleslackapi.events.SlackEvent$1@4b288cbf
corebot_1  | 07:55:21.133 [main] ERROR com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - caught exception in dispatchImpl
corebot_1  | java.io.FileNotFoundException: /opt/corebot/actions.yml (No such file or directory)
corebot_1  | 	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_171]
corebot_1  | 	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_171]
corebot_1  | 	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_171]
corebot_1  | 	at com.gatehill.corebot.config.ConfigServiceImpl.loadCustomConfig(ConfigServiceImpl.kt:197) ~[core-engine-1.2.0.Final.jar:?]
corebot_1  | 	at com.gatehill.corebot.config.ConfigServiceImpl.getJoinMessage(ConfigServiceImpl.kt:137) ~[core-engine-1.2.0.Final.jar:?]
corebot_1  | 	at com.gatehill.corebot.frontend.slack.chat.SlackSessionServiceImpl$connectedListeners$1.onEvent(SlackSessionServiceImpl.kt:44) ~[frontends-slack-1.2.0.Final.jar:?]
corebot_1  | 	at com.gatehill.corebot.frontend.slack.chat.SlackSessionServiceImpl$connectedListeners$1.onEvent(SlackSessionServiceImpl.kt:41) ~[frontends-slack-1.2.0.Final.jar:?]
corebot_1  | 	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl$EventDispatcher.dispatchImpl(SlackWebSocketSessionImpl.java:241) [simple-slack-api-0c58385.jar:?]
corebot_1  | 	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl$EventDispatcher.dispatch(SlackWebSocketSessionImpl.java:204) [simple-slack-api-0c58385.jar:?]
corebot_1  | 	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.establishWebsocketConnection(SlackWebSocketSessionImpl.java:365) [simple-slack-api-0c58385.jar:?]
corebot_1  | 	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connectImpl(SlackWebSocketSessionImpl.java:331) [simple-slack-api-0c58385.jar:?]
corebot_1  | 	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connect(SlackWebSocketSessionImpl.java:285) [simple-slack-api-0c58385.jar:?]
corebot_1  | 	at com.gatehill.corebot.frontend.slack.chat.SlackSessionServiceImpl$session$2.invoke(SlackSessionServiceImpl.kt:32) [frontends-slack-1.2.0.Final.jar:?]
corebot_1  | 	at com.gatehill.corebot.frontend.slack.chat.SlackSessionServiceImpl$session$2.invoke(SlackSessionServiceImpl.kt:20) [frontends-slack-1.2.0.Final.jar:?]
corebot_1  | 	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130) [kotlin-stdlib-1.1.51.jar:1.1.51]
corebot_1  | 	at com.gatehill.corebot.frontend.slack.chat.SlackSessionServiceImpl.getSession(SlackSessionServiceImpl.kt) [frontends-slack-1.2.0.Final.jar:?]
corebot_1  | 	at com.gatehill.corebot.frontend.slack.chat.SlackChatServiceImpl.listenForEvents(SlackChatServiceImpl.kt:42) [frontends-slack-1.2.0.Final.jar:?]
corebot_1  | 	at com.gatehill.corebot.bot.Bot.start(Bot.kt:22) [bots-common-1.2.0.Final.jar:?]
corebot_1  | 	at com.gatehill.corebot.bot.MainKt.main(Main.kt:13) [bots-slack-deploy-1.2.0.Final.jar:?]
corebot_1  | 07:55:21.137 [main] INFO  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - slack session ready
corebot_1  | 07:55:21.138 [main] INFO  com.gatehill.corebot.frontend.slack.chat.SlackSessionServiceImpl - Connected to Slack [persona=jobframework]
`
Here is the output of the file **/opt/corebot/actions.yml**

`cat /opt/corebot/actions.yml
version: '1'
actions:
  services:
    jobId: d60736bf-143f-401e-b73c-aa6ffa03e5f3
    template: deploy services {version} to {environment}
vsa@A001US034SRPT01:/opt/corebot$ 
`

**Comment by outofcoffee** [comment]
Hi @babvin please could you post your compose file?

**Comment by babvin** [comment]
Hello,

Thank you for reverting to solve the issue.

Please find the output as under. I'm running Rundeck on this localhost.

vsa@A001US034SRPT01:~$ cat /opt/corebot/docker-compose.yml
version: '2'

services:
  corebot:
    image: outofcoffee/corebot
    build: ./bots/slack-deploy
    environment:
      SLACK_AUTH_TOKEN: "<token>"
      SLACK_CHANNELS: "cps_jobframework"
      RUNDECK_API_TOKEN: "<token>"
      RUNDECK_BASE_URL: "https://192.168.60.63:4443"

      #   rundeck:
      # image: jordan/rundeck
      #container_name: rundeck
      # environment:
      # SERVER_URL: "https://192.168.60.63:4443"
      #  ports:
      # - "4443:4443"

Thanks in advance,

Best regards,
Vinay
