### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by tanu3195** [outofcoffee/corebot#61]
09:40:27.754 [main] INFO  com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - connecting to slack
Exception in thread "main" java.lang.NullPointerException
	at com.ullink.slack.simpleslackapi.impl.SlackJSONSessionStatusParser.parse(SlackJSONSessionStatusParser.java:71)
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connectImpl(SlackWebSocketSessionImpl.java:335)
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connect(SlackWebSocketSessionImpl.java:294)
	at com.gatehill.corebot.frontend.slack.chat.SlackSessionServiceImpl$session$2.invoke(SlackSessionServiceImpl.kt:32)
	at com.gatehill.corebot.frontend.slack.chat.SlackSessionServiceImpl$session$2.invoke(SlackSessionServiceImpl.kt:20)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
	at com.gatehill.corebot.frontend.slack.chat.SlackSessionServiceImpl.getSession(SlackSessionServiceImpl.kt)
	at com.gatehill.corebot.frontend.slack.chat.SlackChatServiceImpl.listenForEvents(SlackChatServiceImpl.kt:42)
	at com.gatehill.corebot.bot.Bot.start(Bot.kt:22)
	at com.gatehill.corebot.bot.MainKt.runBot(Main.kt:54)
	at com.gatehill.corebot.bot.MainKt.main(Main.kt:33)

**Comment by tanu3195** [comment]
Hi,

We started facing the issue since today morning where we are unable to connect to slack from the container and its keep on exiting.

**Comment by ThomasADavis** [comment]
The Slack API Corebot was using has been disabled.

**Comment by MichaelKueller** [comment]
We are facing the same issue

**Comment by PedroJurado** [comment]
Problem lies in the library that this project uses to connect to slack, so I am afraid they need to upgrade first this other project before is fixed here.

https://github.com/Itiviti/simple-slack-api/issues/299

**Comment by tanu3195** [comment]
Hi All, Please do update with the solution if anyone finds. We will also keep the thread updated with our workarounds.

**Comment by jfabella** [comment]
Hi All,  Saw that the library was fixed, anyone can update this project to use the latest library?


> Problem lies in the library that this project uses to connect to slack, so I am afraid they need to upgrade first this other project before is fixed here.
> 
> [Itiviti/simple-slack-api#299](https://github.com/Itiviti/simple-slack-api/issues/299)

**Comment by outofcoffee** [comment]
Hi folks 👋 Working on the library upgrade in https://github.com/outofcoffee/corebot/issues/63

**Comment by outofcoffee** [comment]
OK, after a bunch of updates (#65, #67, #68), the updated Slack API library has been released in v1.4.0.

Images are up on Docker Hub: https://hub.docker.com/r/outofcoffee/corebot/tags

Please do let me know if this has fixed the issue.

**Comment by outofcoffee** [comment]
Hi folks, thank you for all the feedback!

I'm going to close this issue as resolved, but please do raise a new issue if there are any other problems.
